---
all:
  children:
    pis:
      hosts:
        pi-a:
          ansible_host: 10.20.0.2
          wireguard_enabled: true
          wireguard_interface: wg0
          wireguard_port: 51820
          wireguard_network: 10.30.0.0/24
          wireguard_server_ip: 10.30.0.1
        pi-b:
          ansible_host: 10.20.0.3
          pihole_enabled: true
          pihole_interface: eth0
      vars:
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3

    proxmox:
      hosts:
        pve-01:
          ansible_host: 10.20.0.10
          pve_node_name: pve-01
          hostname: pve-01
          pve_cluster_enabled: false
          vm_id_offset: 100
        pve-02:
          ansible_host: 10.20.0.11
          pve_node_name: pve-02
          hostname: pve-02
          pve_cluster_enabled: false
          vm_id_offset: 200
        pve-03:
          ansible_host: 10.20.0.12
          pve_node_name: pve-03
          hostname: pve-03
          pve_cluster_enabled: false
          vm_id_offset: 300
      vars:
        ansible_user: root
        ansible_ssh_pass: "{{ lookup('env', 'PROXMOX_PASS') }}"
        ansible_python_interpreter: /usr/bin/python3
        pve_template_name: ubuntu-2404-k8s-template
        pve_storage: local-lvm

    k8s_cluster:
      children:
        k8s_control_planes:
          hosts:
            k8s-cp-01:
              ansible_host: 10.20.0.25
              vmid: 100
              memory: 4096
              cores: 2
              disk_size: 40G
              proxmox_node: pve-01
            # k8s-cp-02:
            #   ansible_host: 10.20.0.30
            #   vmid: 200
            #   memory: 2048
            #   cores: 2
            #   disk_size: 30G
            #   proxmox_node: pve-02
            # k8s-cp-03:
            #   ansible_host: 10.20.0.40
            #   vmid: 300
            #   memory: 2048
            #   cores: 2
            #   disk_size: 30G
            #   proxmox_node: pve-03
        k8s_workers:
          hosts:
            k8s-worker-01:
              ansible_host: 10.20.0.26
              vmid: 101
              memory: 6144
              cores: 1
              disk_size: 50G
              proxmox_node: pve-01
            k8s-worker-02:
              ansible_host: 10.20.0.31
              vmid: 201
              memory: 10240
              cores: 2
              disk_size: 50G
              proxmox_node: pve-02
            k8s-worker-03:
              ansible_host: 10.20.0.41
              vmid: 301
              memory: 10240
              cores: 2
              disk_size: 50G
              proxmox_node: pve-03
      vars:
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
